### ISSUE TITLE
Is Windows still not supported?

### ISSUE THREAD

**Issue by tyeeman** [jldec/pub-server#6]
I would like to try this. I'm running Win7. This would be nice - 
```
A 1-click installer which eliminates the need to pre-install node.js and 
use the command-line is coming soon. Fixes for Windows support are also a high priority.
```
What goes wrong when I try to install on Windows?

**Comment by tyeeman** [comment]
So no Windows version for a while then?

**Comment by azure-jldec** [comment]
Hi @tyeeman - Sorry for closing your isssue without notice - i was cleaning up stale issues and got a bit carried away. As you probably noticed, I haven't been very active on this project because of limited resources. Thank you for your interest.

The pub generator does work under windows.

You can `npm install -g pub-server`, then run `pub` in any directory and it will generate a site and serve it at port 3001.
A good example repo to try it out on would be [jldec/pub-doc](https://github.com/jldec/pub-doc). 

The browser-based editor is not working under Windows afaict, but I don't have bandwidth to investigate why. (there is an error on the server side when you click on the edit button). If you would like to investigate and file a PR, i'll make sure I follow up this time :).

I know that the chokidar file watcher which uses `fsevents` doesn't install under windows either (you'll see a message about that during npm install) but that is not the root cause of the editor issues.

The [docs](https://jldec.github.io/pub-doc/) should generally still be accurate, even under windows, so if you find anything there, feel free to file an issue in the pub-doc repo.

hth.
j.
